// client/src/index.tsx
import React from "react";
import ReactDOM from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { createRouter, RouterProvider } from "@tanstack/react-router";
import "./index.css";

import { routeTree } from "./routeTree.gen";

// Create a new router instance
const router = createRouter({ routeTree });

// Register the router instance for type safety
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

const queryClient = new QueryClient();

const root = document.getElementById("root");

if (!root) {
  throw new Error(
    "Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?"
  );
}

ReactDOM.createRoot(root).render(
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </React.StrictMode>
);

// client-solid/src/index.tsx
/* @refresh reload */
import { render } from "solid-js/web";
import { Navigate, Route, Router } from "@solidjs/router";
// import { Store, SwrProvider } from "solid-swr";
// import { LRU, createCache } from "solid-swr/dist/cache";
import "solid-devtools";

import "./index.css";
import { MainLayout } from "./layouts/main";
import { NavMapView } from "./views/navmap";

const root = document.getElementById("root");

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    "Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?"
  );
}

render(
  () => (
    // <SwrProvider value={{ store: new Store(createCache(new LRU())) }}>
    <Router root={MainLayout}>
      <Route path="/navmap" component={NavMapView} />
      <Route path="*" component={() => <Navigate href="/navmap" />} />
    </Router>
    // </SwrProvider>
  ),
  root!
);
